# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Youngeyes.info
email: dr_munish@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Informational site for parent by parents answering questions on young eyes. Please feel free to comment if you have any questions and we'll try to answer the best we can.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: shaunikm
github_username:  munishis

# Build settings
markdown: kramdown
